version: "3"
services:
  db:
    image: postgres
    container_name: apiResponse_db
    environment:
      POSTGRES_DB: apiResponse
      POSTGRES_USER: hatice
      POSTGRES_PASSWORD: ataturk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - apiResponseNetwork
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: apiResponse_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: adiguzell.hatice@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ataturk
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - apiResponseNetwork
    restart: always

  redis:
    image: redis
    container_name: apiResponse_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - apiResponseNetwork
    restart: always

  redis_insight:
    image: redislabs/redisinsight
    container_name: apiResponse_redis_insight
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_data:/db
    networks:
      - apiResponseNetwork
    restart: always

networks:
  apiResponseNetwork:
    driver: bridge

volumes:
  postgres_data: { }
  pgadmin_data: { }
  redis_data: { }
  redis_insight_data: { }
